
CREATE TABLE FUNCIONARIOS (
  MATRICULA INTEGER NOT NULL,
  NOME_FUNC VARCHAR(100) NULL,
  DATA_NASC DATE NOT NULL,
  CPF CHAR(11) NOT NULL,
  COD_DEPTO INTEGER NOT NULL,
  COD_CARGO INTEGER NOT NULL,
  COD_NIVEL INTEGER NOT NULL,
  PRIMARY KEY(MATRICULA)
);

CREATE TABLE SALARIOS (
  COD_CARGO INTEGER NOT NULL,
  COD_NIVEL INTEGER NOT NULL,
  VAL_SALARIO NUMERIC NOT NULL,
  PRIMARY KEY(COD_CARGO, COD_NIVEL)
);

CREATE TABLE CARGOS (
  COD_CARGO INTEGER NOT NULL,
  NOME_CARGO VARCHAR(100) NOT NULL,
  PRE_REQUISITO VARCHAR(100) NULL,
  PRIMARY KEY(COD_CARGO)
);

CREATE TABLE DEPARTAMENTOS (
  COD_DEPTO INTEGER NOT NULL,
  NOME_DEPTO VARCHAR(100) NOT NULL,
  PRIMARY KEY(COD_DEPTO)
);
