SELECT 
NOME_FUNC,
(SELECT NOME_CARGO FROM CARGOS WHERE FUNCIONARIOS.COD_CARGO = CARGOS.COD_CARGO),
(SELECT COD_NIVEL AS "nivel_atual" FROM SALARIOS WHERE FUNCIONARIOS.COD_CARGO = SALARIOS.COD_CARGO AND  FUNCIONARIOS.COD_NIVEL= SALARIOS.COD_NIVEL ),
(SELECT VAL_SALARIO FROM SALARIOS WHERE FUNCIONARIOS.COD_CARGO = SALARIOS.COD_CARGO AND  FUNCIONARIOS.COD_NIVEL = SALARIOS.COD_NIVEL ),
(SELECT COD_NIVEL AS "prox_nivel" FROM SALARIOS WHERE FUNCIONARIOS.COD_CARGO = SALARIOS.COD_CARGO AND  FUNCIONARIOS.COD_NIVEL+1 = SALARIOS.COD_NIVEL ),
(SELECT VAL_SALARIO AS "prox_salario" FROM SALARIOS WHERE FUNCIONARIOS.COD_CARGO = SALARIOS.COD_CARGO AND  FUNCIONARIOS.COD_NIVEL+1 = SALARIOS.COD_NIVEL )
FROM FUNCIONARIOS;


--02
SELECT 
(SELECT NOME_DEPTO FROM DEPARTAMENTOS WHERE DEPARTAMENTOS.COD_DEPTO = FUNCIONARIOS.COD_DEPTO), 
COUNT(FUNCIONARIOS.MATRICULA), SUM(VAL_SALARIO) AS "sal_departamento", ROUND(AVG(VAL_SALARIO), 2)AS "media" 
FROM FUNCIONARIOS, SALARIOS
WHERE FUNCIONARIOS.COD_CARGO = SALARIOS.COD_CARGO 
AND FUNCIONARIOS.COD_NIVEL = SALARIOS.COD_NIVEL
GROUP BY FUNCIONARIOS.COD_DEPTO 
ORDER BY "sal_departamento" DESC;

--03
SELECT NOME_DEPTO, NOME_FUNC, NOME_CARGO, SALARIOS.COD_NIVEL, VAL_SALARIO
FROM DEPARTAMENTOS, FUNCIONARIOS, CARGOS, SALARIOS
WHERE (NOME_DEPTO = 'VENDAS' OR NOME_DEPTO = 'INFORMÁTICA') 
AND (FUNCIONARIOS.COD_DEPTO = DEPARTAMENTOS.COD_DEPTO) 
AND (FUNCIONARIOS.COD_CARGO = CARGOS.COD_CARGO) 
AND (FUNCIONARIOS.COD_CARGO = SALARIOS.COD_CARGO AND FUNCIONARIOS.COD_NIVEL = SALARIOS.COD_NIVEL); 

--04

SELECT 
NOME_CARGO,
(SELECT VAL_SALARIO AS "faixa_1" FROM SALARIOS WHERE CARGOS.COD_CARGO = SALARIOS.COD_CARGO AND  SALARIOS.COD_NIVEL = 1),
(SELECT VAL_SALARIO AS "faixa_2" FROM SALARIOS WHERE CARGOS.COD_CARGO = SALARIOS.COD_CARGO AND  SALARIOS.COD_NIVEL = 2),
(SELECT VAL_SALARIO AS "faixa_3" FROM SALARIOS WHERE CARGOS.COD_CARGO = SALARIOS.COD_CARGO AND  SALARIOS.COD_NIVEL = 4),
(SELECT VAL_SALARIO AS "faixa_5" FROM SALARIOS WHERE CARGOS.COD_CARGO = SALARIOS.COD_CARGO AND  SALARIOS.COD_NIVEL = 5),
(SELECT VAL_SALARIO AS "faixa_6" FROM SALARIOS WHERE CARGOS.COD_CARGO = SALARIOS.COD_CARGO AND  SALARIOS.COD_NIVEL = 6)
FROM CARGOS ORDER BY NOME_CARGO;

-- O WHERE DAS FAIXAIS PRECISAM CONTER AS DUAS PKS POIS A CHAVE É COMPOSTA 